apiVersion: playground.userprovider.crossplane.io/v1alpha1
kind: User
metadata:
  name: example
spec:
  forProvider:
    id: "1"
    name: "John Doe"
    email: "john@example.com"
  # providerConfigRef:
  #   name: example
